import { z } from "zod";
export declare const insertUserSchema: z.ZodObject<{
    username: z.ZodString;
    password: z.ZodString;
    email: z.ZodString;
    firstName: z.ZodString;
    lastName: z.ZodString;
    phone: z.ZodOptional<z.ZodString>;
    role: z.ZodDefault<z.ZodString>;
}, z.core.$strip>;
export declare const insertVehicleSchema: z.ZodObject<{
    make: z.ZodString;
    model: z.ZodString;
    year: z.ZodNumber;
    price: z.ZodNumber;
    mileage: z.ZodNumber;
    exteriorColor: z.ZodString;
    interiorColor: z.ZodOptional<z.ZodString>;
    fuelType: z.ZodString;
    transmission: z.ZodString;
    bodyType: z.ZodString;
    vin: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    features: z.ZodOptional<z.ZodArray<z.ZodString>>;
    images: z.ZodOptional<z.ZodArray<z.ZodString>>;
    status: z.ZodDefault<z.ZodString>;
    isFeatured: z.ZodDefault<z.ZodBoolean>;
    mpg: z.ZodOptional<z.ZodNumber>;
    range: z.ZodOptional<z.ZodNumber>;
    monthlyPayment: z.ZodOptional<z.ZodNumber>;
}, z.core.$strip>;
export declare const insertFinancingApplicationSchema: z.ZodObject<{
    userId: z.ZodOptional<z.ZodNumber>;
    firstName: z.ZodString;
    lastName: z.ZodString;
    email: z.ZodString;
    phone: z.ZodString;
    creditScore: z.ZodString;
    employmentStatus: z.ZodOptional<z.ZodString>;
    annualIncome: z.ZodOptional<z.ZodNumber>;
    vehicleId: z.ZodOptional<z.ZodNumber>;
    status: z.ZodDefault<z.ZodString>;
}, z.core.$strip>;
export declare const insertTestDriveSchema: z.ZodObject<{
    userId: z.ZodOptional<z.ZodNumber>;
    vehicleId: z.ZodNumber;
    firstName: z.ZodString;
    lastName: z.ZodString;
    email: z.ZodString;
    phone: z.ZodString;
    date: z.ZodString;
    time: z.ZodString;
    status: z.ZodDefault<z.ZodString>;
}, z.core.$strip>;
export declare const insertTradeInSchema: z.ZodObject<{
    userId: z.ZodOptional<z.ZodNumber>;
    year: z.ZodNumber;
    make: z.ZodString;
    model: z.ZodString;
    trim: z.ZodOptional<z.ZodString>;
    mileage: z.ZodNumber;
    condition: z.ZodString;
    estimatedValue: z.ZodOptional<z.ZodNumber>;
    status: z.ZodDefault<z.ZodString>;
}, z.core.$strip>;
export type InsertUser = z.infer<typeof insertUserSchema>;
export type InsertVehicle = z.infer<typeof insertVehicleSchema>;
export type InsertFinancingApplication = z.infer<typeof insertFinancingApplicationSchema>;
export type InsertTestDrive = z.infer<typeof insertTestDriveSchema>;
export type InsertTradeIn = z.infer<typeof insertTradeInSchema>;
